### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by nahir31** [ironmansoftware/psedit#11] opened 2022-11-27 09:48 UTC
After typing a parameter with a predefined validate set, would like to see the possible values.
E.g., for -ErrorAction one would expect: Stop, SilentlyContinue, etc.
but currently it just shows the same list of parameters (by the way, including the -ErrorAction that is already used).

Example:
 
![image](https://user-images.githubusercontent.com/12559541/204128831-6967c9b8-469b-47f5-bc36-c6f495a334ae.png)

**Comment by jdhitsolutions** [comment] 2023-02-22 13:54
In v0.0.5, tab-completion works for me. I arrow down to the entry I want and press Tab.

**Comment by adamdriscoll** [comment] 2023-02-27 21:45
I can't reproduce this either. Closing as fixed but please comment if you still have this problem in the latest version.

**Closed by adamdriscoll** 2023-02-27 21:45 UTC
