### ISSUE TITLE
psedit silently fails to start (no errors)

### ISSUE THREAD

**Issue by kborowinski** [ironmansoftware/psedit#20] opened 2023-02-21 16:34 UTC
1. Windows 10.0.19045 with latest patches applied (22H2)
2. PowerShell 7.3.2
3. psedit 0.0.4

![image](https://user-images.githubusercontent.com/16168755/220404540-81c9f9f2-3d13-4b41-873d-5868a87fde3b.png)

**Comment by jdhitsolutions** [comment] 2023-02-21 21:01
I was seeing the same thing, and then I saw an error about a missing component. I think your problem is related to Issue #19 I've tried to manually add what I think the missing packages are, but I'm missing something as I still see the same behavior. Nothing happens, and no errors.  I think there is a requirement we don't know about, or it needs to be included in the module.

**Comment by jdhitsolutions** [comment] 2023-02-21 21:02
I just saw that you responded to *my* issue. Hoping @adamdriscoll will come to the rescue.

**Comment by jdhitsolutions** [comment] 2023-02-21 21:06
I wonder if this typo is the problem: https://github.com/ironmansoftware/psedit/blob/main/ShowEditorCommand.cs#L14

**Comment by jdhitsolutions** [comment] 2023-02-21 21:12
I can manually load the dll. 
![image](https://user-images.githubusercontent.com/12089920/220459600-6ea022b9-8636-46aa-8568-0c89f74f1906.png)

**Comment by jdhitsolutions** [comment] 2023-02-21 21:39
I wonder if it is a runspace issue.

**Comment by kborowinski** [comment] 2023-02-21 22:42
I was able to create the runspace and `terminal.gui.textview` manually after adding `psedit.dll` type but that's all:
![image](https://user-images.githubusercontent.com/16168755/220474404-3fa90996-2479-49c1-bf44-6ca9972b6514.png)

I did try to be sneaky and invoke `ShowEdtiorCommand` directy but in does not work either:
![image](https://user-images.githubusercontent.com/16168755/220475504-d70ab6da-7a85-494f-ada2-da90ce21b54d.png)

I hope that @adamdriscoll can help us too

**Comment by kborowinski** [comment] 2023-02-21 22:58
I tried to use `System.Management.CmdletInfo` class to invoke the cmdlet but it also does not work:
![image](https://user-images.githubusercontent.com/16168755/220477899-4a9b0c34-b506-4860-8d7a-44692900f066.png)

**Comment by jdhitsolutions** [comment] 2023-02-21 22:59
I started down that route as well. I can get a blank terminal GUI to load but that's about it

**Comment by halvarsson** [comment] 2023-02-21 23:00
I had a look and seems like the problem is with NStack.Core, it's referencing 1.0.*, however..

If I change it to use 1.0.5 specifically, then I am able to load the dll and use Show-PSEditor
![image](https://user-images.githubusercontent.com/18571127/220477315-6a94a694-eeef-4cc4-bef0-14e93953f15b.png)

![image](https://user-images.githubusercontent.com/18571127/220478064-84f716f7-9e29-4dde-ba19-8f2957f9451f.png)


But if I build it using the 1.0.* version as defined in the csproj, then we get the following error during Application.Run
![image](https://user-images.githubusercontent.com/18571127/220477454-f142e4d8-9480-4779-a599-2094ce960409.png)

**Comment by kborowinski** [comment] 2023-02-22 07:55
@halvarsson Yep, downgrading `NStack` to *1.0.5* fixes the issue. Thanks.

**Comment by adamdriscoll** [comment] 2023-02-22 13:29
PR has been merged in to fix this. Thanks @halvarsson!! I'll get a release out.

**Closed by adamdriscoll** 2023-02-22 13:29 UTC
